---
deployment:
  tasks:
    - export DEPLOYPATH=/home/iloveshr/news.iloveshrigonda.com/
    - export LOGFILE=/home/iloveshr/deploy.log

    - echo "=== DEPLOY START $(date) ===" >> $LOGFILE

    # Copy application source files
    - /bin/cp -R * $DEPLOYPATH >> $LOGFILE 2>&1

    # Install dependencies and Build
    # NOTE: 'npm' is often not available in the deployment hook environment.
    # Can't run these automatically. You MUST run them manually in cPanel Terminal.
    # - cd $DEPLOYPATH && npm install >> $LOGFILE 2>&1
    # - cd $DEPLOYPATH && npm run build >> $LOGFILE 2>&1

    - echo "=== DEPLOY END $(date) ===" >> $LOGFILE
