---
deployment:
  tasks:
    - export DEPLOYPATH=/home/iloveshr/news.iloveshrigonda.com/
    - export LOGFILE=/home/iloveshr/deploy.log

    - echo "=== DEPLOY START $(date) ===" >> $LOGFILE

    # Copy application source files
    - /bin/cp -R * $DEPLOYPATH >> $LOGFILE 2>&1

    # Install dependencies and Build (Modify if server memory is too low)
    # Note: It's often better to run these manually in cPanel Terminal if they fail here
    - cd $DEPLOYPATH && npm install >> $LOGFILE 2>&1
    - cd $DEPLOYPATH && npm run build >> $LOGFILE 2>&1

    - echo "=== DEPLOY END $(date) ===" >> $LOGFILE
